### PR TITLE
Feature to rewind, fast forward, and start a video at a certain time.

### PR DESCRIPTION
**Pull request by nneuberger1**
Here's the updated feature branch that includes functionality to fast forward and rewind a video.

### CODE REVIEW

**Comment by nneuberger1** [comment]
This is the new branch created with a proper naming convention.

Hold on merging this in. I found one little issue. When isPlaying = false is set, and the startVideoSeconds is set to something, the video starts at 0.0 anyway. I'm trying to figure that out.

**Comment by nneuberger1** [comment]
Ok, I made the fix described in previous comment..

"fixing issue when start at video in seconds is set, but the start of the video was paused. it will now seek to the proper location and then call pause accordingly.  so when start is pressed, it will start at the proper start in seconds time."

**Comment by nneuberger1** [comment]
should be good to test and merge.

**Review by SergioEstevao — APPROVED** [review]
Looking good! thanks for you work on this.

**Comment by nneuberger1** [comment]
Nice! I'm not the greatest at Combine so it's a learning experience. I've got another feature coming up. I'll try and get a PR up for it as well.

**Pull request merged**
